[package]
name = "msgpack_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
rmpv = "1.0.0"

[[bin]]
name = "msgpack_test"
path = "main.rs"
