on: [push]

name: Test

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test

  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./integration-test
    strategy:
      matrix:
        python-version: [3.9, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        continue-on-error: true
        run: |
          poetry install --no-interaction --no-root
      # not sure why installing maturin and pytest is necessary
      - name: Install additional dependencies
        run: |
          poetry run pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.0+cpu.html
      #    poetry run pip install maturin==0.13.5
      #    poetry run pip install pytest
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install rogue-net-rs
        run: poetry run maturin develop --manifest-path=Cargo.toml
      #----------------------------------------------
      # format, type check, and test your code
      #----------------------------------------------

      - name: Run tests
        run: |
          poetry run pytest test.py